App\Application\Model\LancamentoFinanceiro:
    type: entity
    table: lancamento_financeiro
    repositoryClass: App\Repository\LancamentoFinanceiroRepository
    id:
        id:
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: lancamento_financeiro_id_seq
                allocationSize: 1
                initialValue: 1
    fields:
        titulo:
            type: string
            length: 120
        descricao:
            type: string
            nullable: true
            length: 120
        id_categoria:
            type: integer
        custo:
            type: float
        created_at:
            type: datetime